#include "B1BonePostProcessAnimInstance.h"

// No additional implementation needed.
// UB1BonePostProcessAnimInstance derives from UAnimInstance;
// all required UObject boilerplate is generated by GENERATED_BODY().
// The real inZOI logic lives inside the game binary and is invoked at runtime
// when the compiled ABP class resolves to /Script/BlueClient.B1BonePostProcessAnimInstance.
